### PR TITLE
48 resources page

### LINKED ISSUE #48: resources page

### PR DESCRIPTION
**Pull request by bridgetf7**

### CODE REVIEW

**Comment by whydoesthecodenotwork** [comment]
image
i would like a `word-break: break-word;`

**Comment by whydoesthecodenotwork** [comment]
also i don't know how i feel about the entire card growing on hover when only the link is interactable

**Comment by bridgetf7** [comment]
> image i would like a `word-break: break-word;`

This gets resolved in updating-media-queries so I’m waiting for that to be pulled in

**Comment by JakeDangIt** [comment]
this is true the word break is resolved in my repo

**Pull request merged**
